### ISSUE TITLE
Open Source License Clarification

### ISSUE THREAD

**Issue by ssddanbrown** [passwordless/passwordless-server#37]
Hi :wave:, I came across this project via recent blog posts that had been shared to Reddit.
I just wanted to raise that the licensing involved is a little unclear right now, which may impact adoption and contribution. 

This server repo has [a somewhat proprietary license included](https://github.com/passwordless/passwordless-server/blob/82e1cf83ac2d210d0f898041914e913eb83060a2/LICENSE.txt), I couldn't see any other license.
The client doesn't seem to have a license applied. It's `package.json` [states to see a "LICENCE.md" file](https://github.com/passwordless/passwordless-client-js/blob/a5a8443ac3333cf7e79058e02c826d0bf21d7cc1/package.json#L36) but there is no such file in the repo.

The [recent blogpost](https://bitwarden.com/blog/bitwarden-passwordless-dev-hits-general-availability/), [bitwarden passwordless page](https://bitwarden.com/products/passwordless/), [docs pages](https://docs.passwordless.dev/guide/) and [project repos](https://github.com/passwordless/passwordless-client-js/blob/a5a8443ac3333cf7e79058e02c826d0bf21d7cc1/README.md?plain=1#L10) all currently indicate or advertise the project specifically as "open source" but, as far as I can tell, none of the parts involved are provided under what would typically be considered an open source license.

**Comment by abergs** [comment]
Hey @ssddanbrown and thanks for your interest in the project!

The [Javascript client](https://github.com/passwordless/passwordless-client-js) has been updated with a Apache 2.0 license. It was my oversight that we did not publish it sooner. Thanks for keeping me on my toes. 

As for the more general question about our licenses and open source at Bitwarden, I'd like to quote our Licensing FAQ (emphasis mine):

**The source code for all Bitwarden software products is hosted on GitHub and we welcome everyone to review, audit, and contribute to the Bitwarden codebase.**

We believe that making our source code open and available is a defining feature of Bitwarden, and that source code transparency offers critically important customer benefits for security solutions like Bitwarden.

As an open solution, Bitwarden publishes the source code for various modules under different licenses. We're providing [this License Statement and FAQ document](https://github.com/bitwarden/server/blob/master/LICENSE_FAQ.md) as an overview of our licensing philosophy, the specifics of module licensing, and to answer common questions regarding our licenses.

**Comment by ssddanbrown** [comment]
Thanks for the update @abergs!

Based upon your response, I'm assuming the server component is intended to stay under a proprietary, source-available license. In that case, my original point still somewhat remains. The blogpost describes this as an "open source offering", The docs state "All Passwordless.dev code is open source". 

These statements, or generally referring to "passwordless.dev" as open source, may end up misleading folks that think they're choosing to use an open source (and therefore potentially self-hostable) platform, instead of a proprietary platform with an open source client.

As an additional note, the "BITWARDEN LICENSE AGREEMENT", as applied to this repo, is somewhat awkward when applied to a tangential project like this.  A lot of that license is referring to "Commercial Modules" but it's not clear if this comes under that definition, or if it's just "Bitwarden Software". If it's the latter, then not much in that specific license applies outside of limiting liability/warranty/support requirements, and no specific rights are granted or prevented.

**Comment by abergs** [comment]
> These statements, or generally referring to "passwordless.dev" as open source, may end up misleading folks that think they're choosing to use an open source (and therefore potentially self-hostable) platform, instead of a proprietary platform with an open source client.

We try to find a balance between being as open as we possibly can (I and my colleagues care strongly about the open source ecosystem and participate actively in projects) and the requirements of operating a business. We strive to make all code open and available and accepting community contributions.

Also, for self-hosting please follow PR #40 that aims to make the entire project self-hostable with ease.

> As an additional note, the "BITWARDEN LICENSE AGREEMENT", as applied to this repo, is somewhat awkward when applied to a tangential project like this. 

Agreed that we can make it even more clear.
